openapi: 3.0.0
info:
  version: 1.0.0
  title: labofolio admin-bff
  license:
    name: MIT

servers:
  - url: '/v1'

tags:
  - name: system
    description: system relation api

paths:
  ## system 監視
  /ping:
    $ref: './paths/ping.yaml#/ping'